<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>WindowsSshEnabler.Core</RootNamespace>
    <AssemblyName>WindowsSshEnabler.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../WindowsSshEnabler/Core/*.cs" Link="Core/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
